Repository PankajkandpalL/hack-pushnote, pull requests merged in 2023-10, with the labels that each got.

#5 Implement Responsive Navbar Design
  view/index.html
  view/src/App.jsx
  view/src/components/Navbar.jsx
  view/src/components/Navbar/Navbar.jsx
  view/src/components/global/Button.jsx
  view/src/pages/Auth/Login.jsx
  view/src/pages/Auth/Register.jsx
  view/src/pages/Home/Home.jsx
Labels: client-side

#6 User can login, signup and register
  server/.gitignore
  server/logs/combined.log
  server/logs/debug.log
  server/logs/error.log
  server/package.json
  server/src/config/checkEnvConfig.js
  server/src/config/cors/allowedOrigins.js
  server/src/config/cors/corsOptions.js
  server/src/config/dbConfig.js
  server/src/errorHandling/authErrorHandler.js
  server/src/errorHandling/generalErrorHandler.js
  server/src/features/auth/auth.controller.js
  server/src/features/auth/auth.routes.js
  server/src/heathCheckups/healthCheckups.js
  server/src/index.js
  server/src/models/userModel/user.schema.js
  server/src/utils/auth/createUserToken.js
  server/src/utils/common/getUserByToken.js
  server/src/utils/hashPasswords.js
Labels: new, modified, server

#7 implemented auth page
  .vscode/settings.json
  view/.gitignore
  view/package-lock.json
  view/package.json
  view/src/App.jsx
  view/src/Routes/AllRoute.jsx
  view/src/components/Navbar/Navbar.jsx
  view/src/components/global/Button.jsx
  view/src/components/global/Input.jsx
  view/src/main.jsx
  view/src/pages/Auth/Login.jsx
  view/src/pages/Auth/Register.jsx
  view/src/pages/Home/Carousel.jsx
  view/src/pages/Home/Details.jsx
  view/src/pages/Home/Home.jsx
  view/src/pages/Home/Intro.jsx
  view/src/pages/other/Features.jsx
  view/src/pages/other/Price.jsx
  view/tailwind.config.js
Labels: new, client-side

#8 feat(auth): add responsive auth component
  server/logs/combined.log
  server/logs/debug.log
  server/logs/error.log
  view/package-lock.json
  view/package.json
  view/src/components/global/Input.jsx
  view/src/pages/Auth/Login.jsx
  view/src/pages/Auth/OrgInfo.jsx
  view/src/pages/Auth/Register.jsx
  view/src/pages/Auth/Stepper.jsx
  view/src/pages/Auth/UserInfo.jsx
Labels: new, client-side

#9 feat(mails): mail service implemented
  server/logs/combined.log
  server/logs/debug.log
  server/logs/error.log
  server/package.json
  server/src/features/auth/auth.controller.js
  server/src/utils/sendMail.js
Labels: new, server
